version: '3.1'
services:
  mongodb_catalog:
    image: mongo
    container_name: mongo-catalog
    ports:
      - "27019:27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rooot
