server:
    port: 8081
spring:
    application:
        name: movie-service
    datasource:
        driver:
            class: com.mysql.cj.jdbc.Driver
        password:
        url: jdbc:mysql://localhost:3306/moviedb
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
    zipkin:
        base-url: http://localhost:9411
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
