server:
    port: 8082
spring:
    application:
        name: serie-service
    data:
        mongodb:
            #authentication-database: admin
            database: series_db
            #host: localhost
            #password: rooot
            #port: 27017
            #username: root
    rabbitmq:
        addresses: localhost:5672
    zipkin:
        base-url: http://localhost:9411
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
rabbitmq:
    exchanges:
        internal: internal.exchange
    queues:
        notification: notification.queue
    routing-keys:
        internal-notification: internal.notification.routing-key